[project]
name = "medallion-sqlmesh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyodbc>=5.1.0",
    "pyspark>=3.5.3",
    "sqlmesh[postgres,web]>=0.123.4",
]
